# Generated by Django 3.2.2 on 2021-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_point', models.CharField(blank=True, max_length=150, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, max_length=50, null=True)),
                ('travel_time', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('travel_mode', models.CharField(choices=[('Driving', 'Driving'), ('Transit', 'Transit'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Flights', 'Flights')], max_length=30)),
            ],
        ),
    ]
