# Generated by Django 3.2.2 on 2021-05-08 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210508_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_point', models.CharField(blank=True, max_length=150, null=True)),
                ('starting_point', models.CharField(blank=True, max_length=150, null=True)),
                ('destination_location_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('starting_location_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, max_length=50, null=True)),
                ('travel_time', models.DateField(blank=True, null=True)),
                ('starting_time', models.DateField(blank=True, null=True)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('travel_mode', models.CharField(choices=[('Driving', 'Driving'), ('Transit', 'Transit'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Flights', 'Flights')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='store',
        ),
    ]
